### ISSUE TITLE
Document the reason for *not* collecting email addresses

### ISSUE THREAD

**Issue by rylev** [rust-lang/surveys#137]
We have in the past collected email addresses, but we are no longer. We should document why:
* We've never used them in the past
* We often don't have the resources or need to contact people
* It makes data protection more complicated.

**Comment by apiraino** [comment]
I am personally unsure why we should do that (document why de don't need PII anymore). If we don't need them, we just don't gather them and that's it :slightly_smiling_face:  The opposite is instead entirely reasonable.
