### ISSUE TITLE
Document general policy on the use of long-form answers

### ISSUE THREAD

**Issue by rylev** [rust-lang/surveys#15]
Long-form answers are hard to analyze and interpret. We should prefer multiple-choice answers whenever possible with the option of a free form "other" answer.

Whatever our policy ends up being, we should document it.

**Comment by apiraino** [comment]
Some questions are necessarily to be open and long form, when a multiple-choice + "other" are not enough. I am not sure we can codify this into a policy, I think it comes down to the topic of the question:
- multiple-choice are better suited when we think a defined set of answers covers enough surface ("which version of Rust do you use?"). This helps a lot speeding up parsing.
- open and long form are better when we don't want to _suggest_ the solution, show an implied bias or when we want to leave freedom of expressing ideas on multiple axis. Sometime you can use the "other" option an an catchall for this.

Hope this qualifies as a "policy" :slightly_smiling_face:
