### ISSUE TITLE
Define contribution?

### ISSUE THREAD

**Issue by rylev** [rust-lang/surveys#154]
This may not be necessary for the contributors survey as much for the community survey, but I imagine we may want to ensure that what we mean by "contribution" is the same as how respondents interpret the word. I imagine there are likely some people who might not consider being a frequent bug reporter or someone who helps with the triage process as being a "contributor", but we definitely do.

**Comment by yaahc** [comment]
https://github.com/rust-lang/surveys/issues/46#issuecomment-970578349 is how the survey is currently defining it in its questions. We can take the answer options from the first and use those to craft a paragraph description of what we mean when we say contribution. My question is where do we then place that definition to make sure people see it?

**Comment by apiraino** [comment]
merged in #180 (conceptually the same question as #183)
