### ISSUE TITLE
Internal tooling contribution kind

### ISSUE THREAD

**Issue by rylev** [rust-lang/surveys#155]
The "What kind of work" question does not really differentiate bugs/features/etc. for public facing projects (rustc, cargo, etc.) with internal facing code (e.g., bors, perf.rlo, etc.). I wonder if it'd be interesting to find out differences to the contribution experience for those who work on these different aspects of the project.

**Comment by yaahc** [comment]
I think this might be covered currently by the infrastructure section:

```
### Which areas of the project did you contribute to?

Select all that apply:

- rustc
- tools (e.g. cargo, clippy, rustfmt, rustup, etc)
- infrastructure (e.g. highfive, CI, rfcbot, etc)
- libraries (e.g. core, std, libc, log, etc)
- documentation (e.g. rustc-dev-guide, std-dev-guide, forge) (does not include documentation for libraries or rustdoc development)
- website (e.g. rust-lang.org)
- education resources (e.g. rustlings, the book, nomicon, etc)
- Other: Free Form
```

Do you think changing `tools` to `external tools` and adding bors, and perf.rlo as examples after infrastructure would be sufficient? Alternatively I could change the answer to "infrastructure and internal tooling".

**Comment by yaahc** [comment]
I went ahead and did all of the above in https://github.com/rust-lang/surveys/pull/176
