### ISSUE TITLE
future questions: editor/workflow questions

### ISSUE THREAD

**Issue by nrc** [rust-lang/surveys#173]
Finding out which features of an editor people use (even for other langauges) is useful for thinking about what to implement in IDE support and in other tools (e.g., Rustdoc). Some suggestions from Rustdoc folk via Discord were to ask about type hints (inline or on hover), and if these make the respondent more productive.

**Comment by rylev** [comment]
In the interest of keeping the annual survey short, this type of question should be in a different survey.
