### ISSUE TITLE
Create positively framed equivalents of questions that are focused on negative elements of the rust-lang contribution experience

### ISSUE THREAD

**Issue by yaahc** [rust-lang/surveys#182]
The current version of the contributor survey is focused primarily on identifying issues and problems within the rust-lang contribution process, but this current framing is very negative and doesn't currently capture all of the information that we could use to improve the contribution experience. We should additionally add positive equivalents of these questions to identify the positive elements of the rust-lang contribution experience that have had the greatest positive impact since promoting these experiences will be just as important as fixing the negative issues is.

**Comment by yaahc** [comment]
There are two questions in particular that need to be updated:

> Are there any issues or concerns you have regarding the governance and leadership of the teams, project groups, or working groups you participate in?

I'd like to replace this question with the following two questions:

- What are the best elements of the governance and leadership of the teams, project groups, or working groups you participate in?
- What are the worst elements of the governance and leadership of the teams, project groups, or working groups you participate in?


> What are the biggest issues you'd like to see fixed that are negatively impacting your ability to contribute to and/or maintain Rust?

I'd like to keep this question and add this positive alternative question

- What are the elements of the rust-lang contribution experience that have had the greatest positive impact on your ability to contribute to and/or maintain Rust?

**Comment by yaahc** [comment]
Manish suggested adding a followup question to 

> How did you get involved in the Rust Project?

Where we then ask

> What keeps you involved in the Rust Project?

**Comment by apiraino** [comment]
Questions about contributions have been refreshed for the survey 2023 ([link](https://github.com/rust-lang/surveys/blob/main/surveys/2023-annual-survey/questions.md#what-has-your-experience-been-like-in-the-following-rust-community-spaces)) and we thought hard about how to formulate them. I hope they satisfy the ask in this issue.
