### ISSUE TITLE
Questions which are hard to answer for newcomers in 2021 survey

### ISSUE THREAD

**Issue by YohDeadfall** [rust-lang/surveys#185]
The survey contains a few questions which a hard or impossible to answer by newcomers or unexperienced users.

> In your opinion, have the following aspects of Rust gotten better or worse over the past year?

This one can barely answered by a non experienced user and is impossible for a newcomers which have no idea how good it was before.

> Do you agree with the following statements on Rust employment?

That question might be answerable by some participants which recently started learning Rust by taking internship or junior positions. I know at least a few capable to answer people, but for majority this question should be omitted/optional or contain `Unsure`/`Don't know` options.

**Comment by apiraino** [comment]
I hope the set of questions for the survey 2023 is more friendly :-)
