### ISSUE TITLE
Make question number of processors more precise

### ISSUE THREAD

**Issue by YohDeadfall** [rust-lang/surveys#187]
Currently the question about the number of processors used is:

> On the primary machine you compile Rust code on, how many CPUs are there?

It should be fine for most of participants using the English version of the Annual Survey, even if it's not technically correct. The CPU means a physical unit is on a chip and it can be multithreaded.

In Russian "processor" is used instead of CPU which is more direct and correct translation, but as it was pointed out, the most ubiquitous word for that is core.

Don't know how other translations handle that case, but to make the question obvious and technically correct even without reading its description I propose to use "logical processors" instead.

**Comment by nrc** [comment]
We removed this question
