### ISSUE TITLE
Consider a different survey solution

### ISSUE THREAD

**Issue by rylev** [rust-lang/surveys#194]
As of this writing we are using Survey Hero as our survey solution. While there is a lot to like about Survey Hero, there are some downsides. We may want to consider investigating alternatives if we can find one that seems to keep the positives and not have as many of the downsides.

**Pros**
* Good translation mechanisms
* Fairly customizable

**Cons**
* Inability to download the full answer set with the free form answers not included
* Inability to export graphs as SVG
* Not quite powerful enough filtering and query mechanisms of answers

**Comment by Kobzol** [comment]
Does SurveyHero allow exporting the raw data in some form? If we can get e.g. a CSV out, then we can build our own graphs.

**Comment by apiraino** [comment]
For 2023 we're going to use SurveyHero. It's *good enough* though I'm not 100% happy with that (it's not as accessible as I'd like, or at least I can't really *swear* it is because we didn't test) but for the sake of pushing this boulder over the finish line let's call it a day.
