### ISSUE TITLE
Review 'Which operating systems or runtimes do you develop Rust software for?'

### ISSUE THREAD

**Issue by nrc** [rust-lang/surveys#197]
Sorry in advance for vagueness. I found the data for this question difficult to interpret, even with some sophisticated manipulations of the raw data. I think there is some confusion about what targeting a platform means (perhaps some respondents interpret this as 'my code works on that platform' and others as 'I specifically target that platform' (with `cfg`s or Cargo features or whatever). From the point of view of the data, many respondents selected multiple answers, but without any obvious patterns (e.g., it wasn't that people either select one answer or all of them or similar pattern).

I don't have suggestions for how to ask this question better, but it seems like an important data point to have and worth calling out for some re-examination next year.

**Comment by nrc** [comment]
We might want to ask this about projects rather than users some how? And/or make a distinction between libraries and apps?

**Comment by apiraino** [comment]
[This year](https://github.com/rust-lang/surveys/blob/main/surveys/2023-annual-survey/questions.md#which-operating-systems-do-you-use-regularly-for-rust-development) we have:
- Which operating systems do you use regularly for Rust development?
- Which operating systems or runtimes do you develop Rust software for?

Hope it's good enough. Feel free to suggest a different angle to look at this question. For the Survey 2024 :slightly_smiling_face:
