### ISSUE TITLE
Ask about OS version

### ISSUE THREAD

**Issue by nrc** [rust-lang/surveys#202]
For questions about platform, it would be interesting to know which version of an OS is being used

**Comment by kinnison** [comment]
From Rustup's perspective, it's useful to know what platform versions and architectures people are running Rustup on.  This particular need came up because Windows versions go in and out of support and we need to understand what we need to support and at what level.

**Comment by Kobzol** [comment]
Are there particular examples of OSes that you are interested in? I have added WIndows 10/11 vs older Windows to the 2023 survey so far, but we can add more.

**Comment by apiraino** [comment]
For the survey 2023 we have [two questions about OS](https://github.com/rust-lang/surveys/blob/main/surveys/2023-annual-survey/questions.md#which-operating-systems-do-you-use-regularly-for-rust-development):
- Which operating systems do you use regularly for Rust development?
- Which operating systems or runtimes do you develop Rust software for?

Hopefully this will satisfy a number of questions about this topic
