### ISSUE TITLE
Reword 'often felt welcome' option

### ISSUE THREAD

**Issue by iwanders** [rust-lang/surveys#204]
I was reading through the [survey report](https://blog.rust-lang.org/inside-rust/2022/06/21/survey-2021-report.html) today and came across two questions where the given options aren't 100% unambiguous to me. I recall I also ran into this during the survey, but didn't follow up on it then. I'll file one issue for both to allow for easier discussion.

The first one is pertains to the [welcome options](https://github.com/rust-lang/surveys/blob/f7788b3e9671b742ea12eedfd50cecd116412b69/surveys/2021-annual-survey/questions.md?plain=1#L432-L437), the spirit of the answer is clear, so the concern here is relatively minor. But for someone like myself with just a few contributions, checking the 'often felt welcome' option feels awkward because I wouldn't say I've contributed often. I would instead relate the statement to the contributions a person has made. Something along the lines of:
> - I felt welcome with most of the contributions I made.
> - I felt welcome with some of the contributions I made.
> - I've never felt welcome when I made a contribution.
> - I've never participated in this activity.
> - No Response.

This removes the implied need to have contributed often to select the first option.

**Comment by nrc** [comment]
We've basically done this by reducing the number of options
