### ISSUE TITLE
Please display IDE usage in upcoming survey results

### ISSUE THREAD

**Issue by jasonwilliams** [rust-lang/surveys#207]
Hey all

I wanted to know if you could re-include IDE usage in Rust. This was shown every year up until 2019 then for some reason it was no longer included. I think this data is very useful and helps places evaluate the best environment for writing Rust code before diving in. 

After speaking to @rylev my understanding is you do have data on this it's just not shown.

**Comment by apiraino** [comment]
I'll consider this done since we revisited the questions and answers options for the survey 2023

Current choices: https://github.com/rust-lang/surveys/blob/main/surveys/2023-annual-survey/questions.md#which-editor-or-ide-setup-do-you-use-with-rust-code-on-a-regular-basis

**Comment by apiraino** [comment]
I hope next year we can add to the list a few of more Rust IDE projects such as Helix :slightly_smiling_face:
