### ISSUE TITLE
Why translations of survey is so terrible in so many languages?

### ISSUE THREAD

**Issue by wusyong** [rust-lang/surveys#227]
Several of friends of mine have reported that translation of survey this year is terrible.
It feels like it uses google translate and just parses whatever it gets.
So far, I can confirm Simplified Chinese, Traditional Chinese, and Spanish are so awful even regular users can notice.
I fear this will cost community trust as a whole.
What happened this year? And could we update it to make it better?

**Comment by rylev** [comment]
Sorry for this! We tried to make the admin of the survey a bit easier this year, and it bit us in the end. I'm going to work with folks in Zulip on improving the translations.

**Comment by apiraino** [comment]
This year we hope to do a better job with the translations. We could find volunteers for Simplified Chinese (and Spanish) but not for Traditional Chinese. If you want to contribute @wusyong feel free to get in touch (though we're have pretty short on time at this point).

Going to close this issue, thanks for your contribution
