### ISSUE TITLE
Revisit the list of places respondents live

### ISSUE THREAD

**Issue by rylev** [rust-lang/surveys#229]
For the question "where do you live", it's very difficult to provide enough granularity that respondents feel like they can answer truthfully without needing to offer thousands of choices. For this reason, we offer the "other" answer which allows respondents to enter whatever they like. We may want to revisit the list we provide and add any answers the were popular choices to the "other" answer.

**Comment by Kobzol** [comment]
We'd need to know first what were the popular answers :)

**Comment by apiraino** [comment]
In the latest incarnation of the survey we have a scrolldown with just 197 choices. I consider this an improvement over having *thousands* of choices :slightly_smiling_face:

Hopefully it strikes a better balance of granularity vs. convenience.

And, yes, we also have an "Other" option.
