### ISSUE TITLE
State of Rust 2022 results?

### ISSUE THREAD

**Issue by tchernobog** [rust-lang/surveys#233]
The FAQ states that the results should be posted within a couple of months from the survey completion.

We are now close to 5 months.

People have spent time and effort filling in the survey. It would be good to provide a public status update, even if just to state the delay.

Else, participation in the coming years might be lower.

**Comment by rylev** [comment]
Really sorry for the long delay! We're in the process of changing the survey process to be a bit easier on the volunteers who work on the survey, but this is unfortunately causing this year's edition to be a bit delayed. We should have a PR up on the blog repo in the next couple of days. Sorry again for the wait!

**Comment by tchernobog** [comment]
PR at https://github.com/rust-lang/blog.rust-lang.org/pull/1105

**Comment by Kobzol** [comment]
The results of the 2022 survey have been [published](https://blog.rust-lang.org/2023/08/07/Rust-Survey-2023-Results.html).
