### ISSUE TITLE
Moving of results from other surveys

### ISSUE THREAD

**Issue by KodrAus** [rust-lang/surveys#24]
Hey! :wave:

Over in `rust-lang/libs` we have the results from a survey we ran last year: https://github.com/rust-lang/libs-team/tree/main/data/2020-12-11-poisoning-survey

Would those be better migrated here?

**Comment by rylev** [comment]
I think that could be nice - this is certainly meant as a place for central planning of surveys, so the more the merrier, but there's certainly no requirement that you do so.

**Comment by apiraino** [comment]
This question is pretty old but @KodrAus is you're still interested I think you can create a new folder under the directory [./surveys](https://github.com/rust-lang/surveys/tree/main/surveys) by submitting a PR with any content of that survey
