### ISSUE TITLE
Add a "I have no idea" answer to some questions

### ISSUE THREAD

**Issue by Kobzol** [rust-lang/surveys#249]
Seems like some people on Reddit would like that:
- https://www.reddit.com/r/rust/comments/18l7ryc/comment/kdwrmyj
- https://www.reddit.com/r/rust/comments/18l7ryc/comment/kdw0lr5

**Comment by apiraino** [comment]
More screenshots for archiving purposes

<details><summary>Details</summary>
<p>

![grafik](https://github.com/rust-lang/surveys/assets/6098822/9499bde0-a0fe-47f5-aa1a-a7153c9b7b63)


</p>
</details> 


<details><summary>Details</summary>
<p>

![Screenshot 2023-12-19 at 10-12-56 The Rust 2023 Annual survey is here! - r_rust](https://github.com/rust-lang/surveys/assets/6098822/897cc2c0-26d3-4225-bb2f-e6186a9123c3)


</p>
</details>

**Comment by apiraino** [comment]
Note: the second reddit thread are translation fixes, couldnt find anything relevant to this issue

**Comment by Kobzol** [comment]
I have tried to add this to new questions, and when I went through the older ones, I haven't seen a case where I thought it would be needed.
