### ISSUE TITLE
Expand answers to "Are you personally using Rust at work?"

### ISSUE THREAD

**Issue by Kobzol** [rust-lang/surveys#252]
"Majority" and "occasionally" are probably too far away and could use something in between. Noted [here](https://www.reddit.com/r/rust/comments/18l7ryc/comment/kdxdcrq).

**Comment by apiraino** [comment]
Adding a screenshot for archiving purposes

<details><summary>Details</summary>
<p>

![grafik](https://github.com/rust-lang/surveys/assets/6098822/b81698ab-ffd1-4068-b8ac-e10828301cc4)


</p>
</details>
