### ISSUE TITLE
Ask about stdlib features

### ISSUE THREAD

**Issue by Kobzol** [rust-lang/surveys#253]
Our questions about missing features doesn't specifically mention stdlib (e.g. SIMD etc.). It would be nice to add it. Noted on [Reddit](https://www.reddit.com/r/rust/comments/18l7ryc/comment/ke012qy).

**Comment by apiraino** [comment]
Added also a screenshot for archiving purposes

<details><summary>Details</summary>
<p>

![grafik](https://github.com/rust-lang/surveys/assets/6098822/220c1a47-1c4c-4369-bfbb-7b82b0b556fb)


</p>
</details>

**Comment by apiraino** [comment]
Asked t-libs on [Zulip ](https://rust-lang.zulipchat.com/#narrow/stream/219381-t-libs/topic/Rust.20survey.202024)
