### ISSUE TITLE
Somehow make "Please select only the aspects that you have an opinion about" more prominent

### ISSUE THREAD

**Issue by rylev** [rust-lang/surveys#255]
There are some questions where we want users to only give an answer if they really have an opinion on the matter, but the text "Please select only the aspects that you have an opinion about" is very easy to miss. It would be good if we could somehow make this more prominent so that survey takers are less likely to miss it. Perhaps this could be done with use of **bold text** or an **IMPORTANT** marker.

**Comment by apiraino** [comment]
I went through the 2023 and the 2024 (draft) questions and couldn't find that wording or variants of it (maybe I missed that). If a responder does not know what to say, my expectation is to be honest and choose the option "I don't know" :-)

**Comment by Kobzol** [comment]
@rylev Could you please clarify where is "Please select only the aspects..." located?

**Comment by apiraino** [comment]
Going to close this because there was no follow-up. We could revisit this for the survey 2025 (with some examples at hand)
