### ISSUE TITLE
Add a question about familiar technologies

### ISSUE THREAD

**Issue by Kobzol** [rust-lang/surveys#256]
The [2016 survey](https://blog.rust-lang.org/2016/06/30/State-of-Rust-Survey-2016.html) has a question "What programming languages are you most comfortable with?". I think that it would be useful to find out the synergy of Rust with other technologies and to use this question again.

Counterpoint: this data can also be found in other, more general surveys, like JetBrains or StackOverflow survey.

**Comment by apiraino** [comment]
Would that be an interesting actionable for us?

While interesting on a general level, I wonder what would this data point tell us. I think it is interesting for us to understand on which tech ppl use Rust (and there's a question for that).

But I'm open to other opinions: for example a counter-argument could be that it is interesting for us to know that f.e. % of ppl that took the questionaire are in backend development. But that would be a disjointed datapoint from "how do you or your company use Rust for" so I'm not sure how useful to know "what are you familiar with".

Note: every question adds churn to ppl taking the survey, so we should judiciously evaluate each of them :)

**Comment by Kobzol** [comment]
After seeing the latest SO and JetBrains surveys, I would not add this question hete. They have the correlation of Rust with other languages analyzed pretty well.
