### ISSUE TITLE
Better questions for understanding Inclusivity and Representation

### ISSUE THREAD

**Issue by jonnyso** [rust-lang/surveys#261]
Its important to create inclusive and open communities that don't gatekeep or drive away people that want to learn and work, however all the 2023 survey did was a headcount, then jumped to the conclusion that somehow the current state of things isn't great simply based on the proportion of people that identified themselves as a marginalized group. Representation is one indicator of how inclusive a community is, but its not the most important nor should it be the ultimate goal by itself, it also doesn't help much in determining ways to improve and to welcome more people.

In the future it would be beneficial to have questions that help understand a bit more exactly how and why people feel or can affirm that they aren't welcomed or are otherwise impeded from learning or interacting with the community.

Such as:

Is the community hostile towards you ?
Are the resources to learning not easily available to you ?
You are denied access to education ?
Financial reasons ?
Etc.

Rust isn't usually someone's first language, so I think its safe to assume that most people interested in Rust are likely already programmers or involved in STEM in general, even so for people that are trying to get into it, its not a bad idea to promote the Rust community as good and safe space for whoever is interested, and there are also good initiatives such as the Outreachy program.

If anyone was driven away or put off from learning because they're part of a marginalized group, its important to understand how and why so concrete and objective measures can be taken as well as having real metrics to understand if the community is inclusive or not. If you can affirm that:

1 - Learning resources are accessible;
2 - People are welcomed and helped;
3 - The image of the community as whole doesn't put people off;
4 - People are encouraged to join in if they wish.

Then representation has less to do with how inclusive the community is and more to do with external factors.

**Comment by Kobzol** [comment]
Hi, sorry for the late reply. It's true that we haven't analyzed the results of our inclusivity/representation questions much last year (or at least I'm not aware of it). However, I think that it would be better to create a dedicated survey about this, which could ask very detailed and focused questions, rather than trying to put this into the very general annual survey.

We're happy to run such a survey, if we get some proposals for how it should look like.

**Comment by apiraino** [comment]
I'm going to close this as we didn't receive an actionable feedback. Happy to talk about that, though. Feel free to open a proposal on [Zulip](https://rust-lang.zulipchat.com/#narrow/channel/402479-t-community.2Frust-survey).
