### ISSUE TITLE
License the `surveys` repository under the MIT/Apache-2.0 license

### ISSUE THREAD

**Issue by Kobzol** [rust-lang/surveys#267]
This repository currently does not have a top-level LICENSE file, which means that its code is not covered by a license.
We would like to license the `surveys` repository under the dual MIT/Apache-2.0 License.

Note that the license pertains to the code and Markdown files in this repository, not to the contents or results of the performed surveys themselves.

To do that, **we need contributors that made commits to this repository to agree by posting a comment stating their approval to this issue**. Please see instructions at the bottom of this issue if you are mentioned in the list below. I will try to also contact the contributors individually.

PR with the new license: https://github.com/rust-lang/surveys/pull/266

# Checkoff
To agree to the licensing terms, please comment with the following text on this issue (you can copy the text using the copy button on the right):
```
I license my contributions to the `rust-lang/surveys` repository under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.
```
Thank you very much!

Affected contributors:

- [x] @rylev
- [x] @nrc
- [x] @Kobzol
- [x] @yaahc
- [x] @joshtriplett
- [x] @YohDeadfall
- [x] @apiraino
- [x] @JasunC
- [x] @skade
- [x] @graciegregory
- [x] @legoktm
- [x] @ehuss
- [x] @JoelMarcey
- [x] @alice-i-cecile

**Comment by Kobzol** [comment]
I license my contributions to the `rust-lang/surveys` repository under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by YohDeadfall** [comment]
I license my contributions to the rust-lang/surveys repository under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by ehuss** [comment]
I license my contributions to the `rust-lang/surveys` repository under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by legoktm** [comment]
I license my contributions to the `rust-lang/surveys` repository under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by JasunC** [comment]
I license my contributions to the `rust-lang/surveys` repository under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by JoelMarcey** [comment]
I license my contributions to the `rust-lang/surveys` repository under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by graciegregory** [comment]
I license my contributions to the rust-lang/surveys repository under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by alice-i-cecile** [comment]
I license my contributions to the rust-lang/surveys repository under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by nrc** [comment]
I license my contributions to the `rust-lang/surveys` repository under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by rylev** [comment]
I license my contributions to the `rust-lang/surveys` repository under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by joshtriplett** [comment]
I license my contributions to the `rust-lang/surveys` repository under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by skade** [comment]
I license my contributions to the rust-lang/surveys repository under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by yaahc** [comment]
I license my contributions to the `rust-lang/surveys` repository under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by Kobzol** [comment]
Great, we got all! Thank you everyone :)
