### ISSUE TITLE
What kind of work do you do within the rust project?

### ISSUE THREAD

**Issue by yaahc** [rust-lang/surveys#46]
https://github.com/yaahc/surveys/blob/collab-questions/surveys/2021-contributor-survey/questions.md#what-kind-of-work-do-you-do-within-the-rust-project

This question is trying to identify cohorts of responsibilities within the rust projects. Individuals who mostly implement new features are going to encounter different problems than those who mainly review other's contributions.

The answers of this question are an attempt to exhaustively enumerate all the ways people can contribute to the Rust Project.

The current set of options we have is clearly a poor breakdown of the responsibilities that exist within the project and is in need of refinement.

- contribution work
- maintainership work
- reviews
- coordination
- organization

**Comment by yaahc** [comment]
## New list

* Documentation
* Code Review (PRs)
* Design Review (RFCs/MCPs/FCPs)
* Issue Triage

## New list candidates that need refinement/deduplication/etc

* Governance
* Management
  * Project
  * Product
* Coordination / Organization

**Comment by yaahc** [comment]
The copy in the survey has been updated and now looks like this:

```md
### What kind of work do you do within the Rust Project?

Select all that apply:

- Documentation
- Code Review (PRs)
- Design Review (RFCs/MCPs/FCPs)
- Issue Triage
- Issue Reporting
- Moderation
- New Features
- Bug Fixes
- Performance enhancements
- Communication (e.g. writing blog posts, release notes, preparing for meetings or taking minutes)
- supporting/mentoring/guiding other contributors
- Rollups/CI/Releases
- Governance
- Other: Free Form

> **justification**
>
> Useful for cohort analysis. Problems will likely differ based on the work
> being done. Those contributing new code will likely face diff problems than
> those who mainly review or coordinate work.

### Which areas of the project have you contributed to?

Select all that apply:

- rustc
- external tools (e.g. cargo, clippy, rustfmt, rustup, etc)
- infrastructure and internal tools (e.g. highfive, CI, rfcbot, bors, perf.rlo, etc)
- libraries (e.g. core, std, libc, log, etc)
- documentation (e.g. rustc-dev-guide, std-dev-guide, forge) (does not include documentation for libraries or rustdoc development)
- website (e.g. rust-lang.org)
- education resources (e.g. rustlings, the book, nomicon, etc)
- Other: Free Form

> **justification**
>
> Useful for cohort analysis. The part of the project that the user is involved
> in can have implications for what types of pain points they would run into.
> For example, pain points for contribution work will be different if you're a
> tool developer (e.g. the processes for syncing with the main rust-lang/rust
> repo, or with API stability in the compiler or something like that) or a
> rustc developer (e.g. how long it takes a PR to land, build times, etc.).
```

This should hopefully be sufficiently comprehensive and help us group feedback by area and kind of contribution.

**Comment by apiraino** [comment]
heh ... I wish we included more specific questions about this topic but we also tried to not make the survey too long.

But I like the concept behind this idea and I'll earmark it by linking it to #188 .

Closing since we decided to skip this.
