### ISSUE TITLE
Community Cloud Machines survey

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/surveys#52]
We want to find out a few things for the cloud machine project:

* how many cores do you have right now
* where are you located (country or just a list of regions?)
* what platforms do you need (linux, mac, windows, arm, ...?)
* what do you plan on using these machines for (freeform text field)

**Comment by oli-obk** [comment]
@rylev do you think it could make sense to include some of those questions in the big 2021 survey under the section for Rust contributors?

**Comment by apiraino** [comment]
yeah let's run a focused minipoll about this

#188
