### ISSUE TITLE
Generalized Survey FAQ

### ISSUE THREAD

**Issue by yaahc** [rust-lang/surveys#59]
The annual survey links to a FAQ that describes the survey policy related to emails and anonymity. We might want to generalize this FAQ into a general survey policy that we can link in all of our surveys.

**Comment by yaahc** [comment]
related to https://github.com/rust-lang/surveys/pull/45

**Comment by apiraino** [comment]
I think this issue is satisfied [by this page](https://forge.rust-lang.org/community/survey-faq.html)
