### ISSUE TITLE
Evaluate cross-cohort question consistency for collaboration survey

### ISSUE THREAD

**Issue by yaahc** [rust-lang/surveys#61]
The answer users give to the first question in the collaboration survey determines which questions we follow up with. This first question breaks up our answers into major cohorts depending on how the user has contributed to the project, such as an active contributor vs a potential contributor. In many cases however the questions we ask the different are similar, and before we release the survey we should double check all the questions we're asking each cohort to make sure we're asking the same questions in each cohort where said question would be relevant.

**Comment by yaahc** [comment]
related to https://github.com/rust-lang/surveys/pull/45

**Comment by yaahc** [comment]
The governance questions asked in the active contributor survey are not all represented in the inactive contributor survey but would apply and should be copied over and reworded to use the past tense.

**Comment by apiraino** [comment]
I am honestly struggling to translate into actionables the ask formulated in this issue :slightly_smiling_face: Possibly, the context it was formulated is not applicable anymore
