### ISSUE TITLE
Finish design.md documents

### ISSUE THREAD

**Issue by rylev** [rust-lang/surveys#64]
Our approach with the design.md document was to think about higher-level questions before focusing of specific questions we would ask on the survey. Once we made progress on this, we decided to shift gears towards the survey questions themselves. Now that we've made more progress on the actual survey questions, we should return to the design documents and make sure our reasoning for how we designed the survey are properly captured.

**Comment by apiraino** [comment]
The approach we adopted in the last 2 or 3 iterations of the survey is to start from the previous year's dataset of questions and change/tune things. A design document is probably not needed anymore.
