### ISSUE TITLE
Ensure that the edition working group is fine with the lack of questions about editions

### ISSUE THREAD

**Issue by rylev** [rust-lang/surveys#71]
In the past we've asked about how smoothly or uneventful respondent's experience with upgrading an edition has been. We have removed these questions from the survey because presumably the edition *should* be a non-event, and bug reports are a better indicator of if this is true or not.

cc @m-ou-se @nikomatsakis

**Comment by nikomatsakis** [comment]
I think that's ok, also because the edition is coming out around the same time as the survey, most likely.
