### ISSUE TITLE
Where is the course or activity taught?

### ISSUE THREAD

**Issue by badboy** [rust-lang/surveys#88]
[Link to question](https://github.com/rust-lang/surveys/blob/5685410a8e7c134015b2b111d069ac771508bfb3/surveys/2021-annual-survey/questions.md#where-is-the-course-or-activity-taught)

Curious why the answers leave out other course options of continuing education, e.g. Udemy or similar, that someone could do on their own.

**Comment by rylev** [comment]
This is a good point. I think we were likely thinking that people should check off vocational-focused educational institute, but MOOC feel categorically different.
