### ISSUE TITLE
Move previous years answers to a dedicated location owned by the foundation

### ISSUE THREAD

**Issue by rylev** [rust-lang/surveys#9]
It's unclear (to me) where the previous years questions and results are stored. We should make sure that this data is stored in a secure place with proper permissions (most likely owned by the foundation).

**Comment by apiraino** [comment]
questions are on github, answers datasets are handled by the Foundation. We will clarify this point after the survey 2023 has officially closed.

**Comment by apiraino** [comment]
Clarified survey raw dataset holders in https://github.com/rust-lang/rust-forge/pull/781
